### ISSUE TITLE
PROJECT: Add CircleCI

### ISSUE THREAD

**Issue by oliva20** [JoshMoule/SOFTWARE-SYSTEMS-DEVELOPMENT#3]
CircleCI is a great tool that checks for build errors everytime a commit is made. It automatically builds the program everytime you try to push it to the repo. If the doesn't build than the push won't pass.

If anyone is interested and wants to know how to implement it, here's a great chance to do so.

It might also give us some extra marks who knows.

**Comment by shashanknehra** [comment]
I am trying to implement it
